### ISSUE TITLE
Badge count is not cleared.

### ISSUE THREAD

**Issue by ringods** [sharkpp/franz-recipe-mastodon#1]
Hello @sharkpp, thanks for your Franz Mastodon recipe. 

I have set it up in `dev` mode in my Franz 5.0-beta.18. I have set up my account on `mastodon.social` and it works ok. The badge count goes up when there is a notification. But after checking the notification and even clearing it, the badge count still stands there. We are currently 5 hours later but the badge count is still there.

When additional notifications come in, the badge count goes up. Again, it doesn't get cleared, even if I clear my Mastodon notifications. Do you know what is wrong here?

**Comment by sharkpp** [comment]
Yes, I could confirm the problem.
The latest version seems to be unable to detect the active / inactive of the service.
Probably this is considered to be the cause.

**Comment by kizu** [comment]
Can confirm, has the same problem on my site. The simplest workaround for the time being: just refresh the service, the badge would go away. But it would be nice to get it fixed somehow!

**Comment by sharkpp** [comment]
Maybe fixed. Please check with new version.
> たぶん修正できてる。なので新しいバージョンで確認してみてください。
